/**
 * data for action types
 * @author:Shravya P
 */
const ActionTypes = {
  SET_DEALS: 'SET_DEALS',
  SET_DISCOUNTS: 'SET_DISCOUNTS',
  SET_SELECTIONS: 'SET_SELECTIONS',
  SET_LOGIN: 'SET_LOGIN',
  SET_PRODUCTS: 'SET_PRODUCTS',
  SET_PRODUCT: 'SET_PRODUCT',
  SET_CATEGORY: 'SET_CATEGORY',
  SET_CART: 'SET_CART',
  ADD_TO_CART: 'ADD_TO_CART',
  UPDATE_CART: 'UPDATE_CART',
  DELETE_CART: 'DELETE_CART',
  SET_ADDRESS: 'SET_ADDRESS',
  SET_ORDER: 'SET_ORDER',
  SET_TOTAL_COST: 'SET_TOTAL_COST',
  SET_EMPTY_CART: 'SET_EMPTY_CART',
};
export default ActionTypes;
