/**
 * Contains all the constant data that are used in the application.
 * @author:Shravya P
 */
import React from 'react';
import { IoIosArrowDown } from 'react-icons/io';

export const CarouselData = [
  'https://rukminim1.flixcart.com/flap/1688/280/image/1b4cc9f62ac9ee97.jpg?q=50',
  'https://rukminim1.flixcart.com/flap/1688/280/image/30a361b00075c80e.jpg?q=50',
  'https://rukminim1.flixcart.com/flap/844/140/image/fb549ccc7b6b5d46.jpg?q=50',
  'https://rukminim1.flixcart.com/flap/1688/280/image/6606d49bbc0af95f.jpg?q=50',
];

export const navData = [
  {
    url: 'https://rukminim1.flixcart.com/flap/128/128/image/f15c02bfeb02d15d.png?q=100',
    text: 'Top Offers',
  },
  {
    url: 'https://rukminim1.flixcart.com/flap/128/128/image/29327f40e9c4d26b.png?q=100',
    text: 'Grocery',
  },
  {
    url: 'https://rukminim1.flixcart.com/flap/128/128/image/22fddf3c7da4c4f4.png?q=100',
    text: 'Mobile',
  },
  {
    url: 'https://rukminim1.flixcart.com/flap/128/128/image/82b3ca5fb2301045.png?q=100',
    text: 'Fashion',
    category: 'fashion',
    icon: <IoIosArrowDown style={
            {
              paddingLeft: '3px',
              marginTop: 3,
            }
        }
    />,
  }, {
    url: 'https://rukminim1.flixcart.com/flap/128/128/image/69c6589653afdb9a.png?q=100',
    text: 'Electronics',
    category: 'electronics',
    icon: <IoIosArrowDown style={
            {
              paddingLeft: '3px',
              marginTop: 3,
            }
        }
    />,
  }, {
    url: 'https://rukminim1.flixcart.com/flap/128/128/image/ab7e2b022a4587dd.jpg?q=100',
    text: 'Home',
    category: 'home',
    icon: <IoIosArrowDown style={
            {
              paddingLeft: '3px',
              marginTop: 3,
            }
        }
    />,
  }, {
    url: 'https://rukminim1.flixcart.com/flap/128/128/image/0ff199d1bd27eb98.png?q=100',
    text: 'Appliances',
    category: 'appliances',
    icon: <IoIosArrowDown style={
            {
              paddingLeft: '3px',
              marginTop: 3,
            }
        }
    />,
  }, {
    url: 'https://rukminim1.flixcart.com/flap/128/128/image/71050627a56b4693.png?q=100',
    text: 'Travel',
  }, {
    url: 'https://rukminim1.flixcart.com/flap/128/128/image/dff3f7adcf3a90c6.png?q=100',
    text: 'Beauty, Toys & More',
    category: 'BeautyToysAndMore',
    icon: <IoIosArrowDown style={
            {
              paddingLeft: '3px',
              marginTop: 3,
            }
        }
    />,
  },
];

export const drawerData = [
  'SuperCoin Zone',
  'Flipkart Plus Zone',
  'Electronics',
  'Fashion',
  'Home and furnitures',
  'TVs & Appliances',
  'Toys and Baby',
  'Beauty and personal care',
  'Sports Books & More',
  'Refurbished Products',
  'Flights',
];

export const categories = {
  fashion: {
    "Mens's Top Wear": [
      "MORE IN MEN'S TOP WEAR",
      'All',
      "Men's T-Shirts",
      "Men's Casual Shirts",
      "Men's Formal Shirts",
      "Men's Kurtas",
      "Men's Ethnic Sets",
      "Men's Blazers",
      "Men's Raincoat",
      "Men's Windcheaters",
      "Men's Suit",
      "Men's Fabrics",
    ],
    "Men's Bottom Wear": [
      "MORE IN MEN'S BOTTOM WEAR",
      'All',
      "Men's Jeans",
      "Men's Trousers",
      "Men's Trackpants",
      "Men's Shorts",
      "Men's Cargos",
      "Men's Threefourths",
      "Men's Pyjamas & Loungepants",
      "Men's Dhoti",
      "Men's Ethnic Pyjama",
    ],
    'Women Ethnic': [
      'MORE IN WOMEN ETHNIC',
      'All',
      'Women Sarees',
      'Women Kurtas & Kurtis',
      'Women Kurta Sets & Salwar Suits',
      'Ethnic Dresses',
      'Women Dress Materials',
      'Women Gowns',
      'Women Lehenga Cholis',
      'Women Leggings & Patialas',
      'Women Palazzos & Shararas',
      'Women Blouse',
      'Women Dupatta',
    ],
    'Women Western': [
      'MORE IN WOMEN WESTERN',
      'All',
      'Women Tops',
      'Women Dresses',
      'Women T-shirts & Polo T-shirts',
      'Women Jeans',
      'Women Nighties & Night Dresses',
      'Women Nightsuit',
      'Women Track Pants',
      'Women Trouser',
      'Women Jumpsuit',
      'Women Shapewear',
      'Women Sports Bra',
    ],
    'Men Footwear': [
      'MORE IN MEN FOOTWEAR',
      'All',
      "Men's Sports Shoes",
      "Men's Casual Shoes",
      "Men's Sandals & Floaters",
      "Men's Slippers & Flip Flops",
      "Men's Formal Shoes",
      "Men's Ethnic Shoes",
      'Active Footwear',
      'Combo Footwear',
      'Shoe Care',
    ],
    'Women Footwear': [
      'MORE IN WOMEN FOOTWEAR',
      'All',
      'Women Flats',
      'Women Heels',
      'Women Wedges',
      'Women Slipper Flip Flops',
      'Women Casual Shoes',
      'Women Sports Shoes',
      'Women Ballerinas',
      'Women Ethnic Shoes',
      'Women Sneakers',
      'Women Walking Shoes',
      'Women Boots',
    ],
    'Watches and Accessories': [
      ' MORE IN WATCHES AND ACCESSORIES',
      'Men & Women Watches',
      'Men & Women Sunglasses',
      'Wallets',
      'Men & Women Belts',
      'Women Fashion Jewellery',
      'Men Fashion Jewellery',
      'Precious Jewellery',
      'Precious Coins & Bars',
      'Precious Articles',
      'Frames & Contact Lenses',
      'Kids Accessories',
    ],
    'Bags, Suitcases &amp; Luggage': [
      'MORE IN BAGS, SUITCASES & LUGGAGE',
      'All',
      'Backpacks',
      'Suitcases & Trolleys',
      'Dufflebags',
      'Rucksacks',
      'Handbags',
      'Slingbags',
      "Women's Clutches & Wallets",
      'Messenger Bags',
      'Travel Accessories',
    ],
    Kids: [
      'MORE IN KIDS',
      'All',
      'Girls Dresses',
      'Boys & Girls Tshirts',
      'Boys & Girls Combosets',
      'Boys & Girls Ethnic Wear',
      'Boys & Girls Jeans',
      'Boys & Girls Shorts',
      'Boys & Girls Trackpants',
      'Boys & Girls Innerwear',
      'Infant Wear',
      'Kids Slipper Flip Flops',
      'Kids Sports Shoes',
    ],
    Essentials: [
      'MORE IN ESSENTIALS',
      "Men's Briefs & Trunks",
      "Men's Vests",
      "Men's Boxers",
      'Women Lingerie Sets',
      'Women Bra',
      'Women Panty',
      'Women Sarees',
      'Women Kurtas',
      'Women Kurta Sets & Salwar Suits',
      'Boys Innerwear',
      'Boys Innerwear',
      'Girls Innerwear',
      'Women Slipper Flip Flops',
    ],
    Winter: [
      'MORE IN WINTER',
      'All',
      "Men's Jackets",
      "Men's Sweatshirts",
      "Men's Sweaters",
      "Men's Thermals",
      "Women's Jackets",
      "Women's Sweatshirts",
      "Women's Sweaters & Cardigans",
      "Women's Shrugs",
      'Kids SweatShirts',
      'Women Kurtas',
      'Kids Jackets',
    ],
  },
  electronics: {
    Audio: [
      'MORE IN AUDIO',
      'All',
      'Bluetooth Headphones',
      'Wired Headphones',
      'True Wireless Earbuds',
      'Bluetooth Speakers',
      'Soundbars',
      'Home Theatres',
      'TV Streaming Device',
      'Remote Control',
      'DTH Set top box',
      'Headphones Pouch & Case Covers',
    ],
    'Electronics GST Store': [],
    'Cameras & Accessories': [
      'MORE IN CAMERAS & ACCESSORIES',
      'All',
      'DSLR & Mirrorless',
      'Sports & action',
      'Point & Shoot',
      'Instant Cameras',
      'Camcorders',
      'Camera tripods',
      'Camera Lenses',
      'Drone',
      'Flashes',
      'Gimbals',
      'Binoculars',
      'Other Camera Accessories',
    ],
    'Computer Peripherals': [
      'MORE IN COMPUTER PERIPHERALS',
      'All',
      'Printers',
      'Monitors',
      'Projectors',
      'Portable Projectors',
      'Toners',
      'Ink Cartridges',
      'Ink Bottles',
      'Receipt Printers',
      'Lamination Machines',
      'Note Counting Machines',
      'Barcode Scanners',
      'Currency Detectors',
    ],
    Gaming: [
      'MORE IN GAMING',
      'All',
      'Gaming Consoles',
      'Gaming Mouse',
      'Gaming Keyboards',
      'Gamepads',
      'Games',
      'Accessory Kits',
      'Gaming Accessories Combo',
      'Gaming Mousepads',
      'Membership Cards',
      'Controllers',
      'Other Gaming Accessories',
      'Gaming Components',
    ],
    'Health & Personal Care': [
      'MORE IN HEALTH & PERSONAL CARE',
      'All',
      'Trimmers',
      'Shavers',
      'Hair Straighteners',
      'Hair Dryers',
      'Epilators',
      'Glucometers And Accessories',
      'Blood Pressure Monitors',
      'Digital Thermometers',
      'Weighing Scales',
      'Massagers',
      'Nebulizers',
      'Vaporizers',
    ],
    'Laptop Accessories': [
      'MORE IN LAPTOP ACCESSORIES',
      'All',
      'Mouse',
      'Laptop Keyboards',
      'Router',
      'Data Cards',
      'UPS',
      'USB Gadgets',
      'Security Software',
      'Laptop Battery',
      'Laptop Adapter',
      'Wireless USB Adapter',
      'Processor',
      'Other Accessories',
    ],
    'Laptop and Desktop': [
      'MORE IN LAPTOP AND DESKTOP',
      'All',
      'Laptops',
      'Gaming Laptops',
      'Desktop PCs',
      'All In One PCs',
      'Mini PCs',
      'Tower PCs',
      'PC Finder',
      'GST Invoice on Laptops',
      'Laptop Buying Guide',
    ],
    MobileAccessory: [
      'MORE IN MOBILEACCESSORY',
      'All',
      'Plain Cases',
      'Designer Cases',
      'Screen Guards',
      'Camera Lens Protectors',
      'Tablet Accessories',
      'MobileCable',
      'MobileChargingMobileCharger',
      'MobilePouches',
      'MobileFlash',
      'MobileHolder',
      'MobileUSBGadget',
      'Mobiles Accessories Combos',
    ],
    Powerbank: [
      'MORE IN POWERBANK',
      'All',
      'Powerbank',
    ],
    'Smart Home automation': [
      'MORE IN SMART HOME AUTOMATION',
      'All',
      'Smart Assistants',
      'Smart Lights',
      'Smart Cameras',
      'Smart Switches',
      'Smart Door locks',
      'Sensors & Alarms',
    ],
    'Smart Wearables': [
      'MORE IN SMART WEARABLES',
      'All',
      'Smart Watches',
      'Smart Bands',
      'Smart Glasses',
    ],
    Storage: [
      'MORE IN STORAGE',
      'All',
      'MobileMemoryCard',
      'ComputerStoragePendrive',
      'MobileStoragePendrive',
      'ExternalHardDrive',
      'InternalHardDrive',
    ],
    Tablets: [
      'MORE IN TABLETS',
      'All',
      'Tablets With Call Facility',
      'Tablets Without Call Facility',
    ],
  },
  home: {
    'Home Furnishings': [
      'MORE IN HOME FURNISHINGS',
      'All',
      'Bed Linens',
      'Bedsheets',
      'Blankets',
      'Curtains & Accessories',
      'Bath linen',
      'Floor coverings',
      'Covers & protectors',
      'Cushions & Pillows',
      'Kitchen Linen Sets',
      'Table Linen Sets',
      'Sofa & curtain fabrics',
      'Branded Collections',
    ],
    'Living Room': [
      'MORE IN LIVING ROOM',
      'All',
      'Sofas Sets & Sectionals',
      'TV Units',
      'Dining Sets',
      'Coffee Tables',
      'Sofa Beds',
      'Recliners',
      'Living Room Chairs',
      'Cabinet & Drawers',
      'Bookshelves',
      'Shoe Racks',
      'Office Tables',
      'Office Chairs',
    ],
    'Kitchen & Dining': [
      'MORE IN KITCHEN & DINING',
      'All',
      'Cookware',
      'Lunchboxes, Bottles & Flasks',
      'Knives, Choppers & Cutters',
      'Gas Stoves & Accessories',
      'Kitchen tools',
      'Tableware & Dinnerware',
      'Containers & Kitchen Storage',
      'Barware',
      'Bakeware',
      'Handjuicers & Grinders',
      'Disposable Supplies',
      'Outdoor cooking',
    ],
    'Bedroom room': [
      'MORE IN BEDROOM ROOM',
      'All',
      'Mattresses',
      'Beds',
      'Wardrobes',
      'Side Tables',
      'TV Units',
      'Office Tables',
      'Office Chairs',
      'Bookshelves',
      'Bar Cabinets',
      'Bar Stools',
      'Rocking Chairs',
      'Benches',
    ],
    'Home Decor': [
      'MORE IN HOME DECOR',
      'All',
      'Lightings',
      'Stickers & Wallpapers',
      'Paintings & Posters',
      'Clocks',
      'Showpieces & Decoratives',
      'Wall Decor',
      'Flowers & Vases',
      'Home Fragrances',
      'Windchimes & Dream catcher',
      'Photo frames & Albums',
      'Diyas, Candles & Holders',
      'Festive & Giftng',
    ],
    'Tools & Utility': [
      'MORE IN TOOLS & UTILITY',
      'All',
      'Hand tools',
      'Power Tools',
      'Measuring Tools',
      'Home Storage & Organizers',
      'Umbrellas',
      'Appliance Trolley & Stands',
      'Cloth Dryer Stand',
      'Appliance Filter & Cartridges',
      'Laundary Organization',
      'Lock & Security',
      'Fire & Personal Safety',
      'Paint Supplies & Equipments',
    ],
    'Lightings & Electricals': [
      'MORE IN LIGHTINGS & ELECTRICALS',
      'All',
      'Bulbs',
      'Emergency Lights',
      'Torches',
      'Tubelights',
      'Extension Cords',
      'Outdoor Lamps',
      'Batteries',
      'ElectricalWire',
      'ElectricalSocket',
      'ElectricDoorBell',
      'Solar Lights, Panels & Batteries',
      'Electrical Hardware',
    ],
    'Space Saving': [
      'MORE IN SPACE SAVING',
      'All',
      'Portable Laptop Tables',
      'Collapsible Wardrobes',
      'Bean Bags & Covers',
      'Shoe Racks',
      'Cabinet Drawers',
      'Inflatable Sofas',
      'Hammock Swings',
      'Home Temples',
      'Bookshelves',
      'TV Mounts',
      'Kitchen Trolley',
      'Kitchen Cabinet',
    ],
    'Cleaning & Bath': [
      'MORE IN CLEANING & BATH',
      'All',
      'Mops',
      'Cleaning Supplies',
      'House Hold supplies',
      'Air Fresheners',
      'Cleaning Gloves',
      'Liquid Detergents',
      'Taps & Faucet',
      'Toothbrush holder',
      'Bathroom Rack & Shelves',
      'Shower Heads',
      'Bath & Kitchen Fittings',
      'Bathroom Accesorries',
    ],
    'Kids Furniture': [
      'MORE IN KIDS FURNITURE',
      'All',
      'Bunk Beds',
      "Kids' Seating",
      "Kids' Table",
      "Kids' Chairs",
      "Kids' Sofas",
      'Bookshelves',
      'Chest of Drawers',
      'Cupboards',
      'Shoe Racks',
      "Kids' Bean Bags",
      'Portable Pool',
      'Sofa Beds',
    ],
    'Pet & Gardening': [
      'MORE IN PET & GARDENING',
      'All',
      'Plant Seeds',
      'Soil Manure',
      'Pots & Planters',
      'Plant & Planters',
      'garden tool set',
      'watering Equipments',
      'Dog Essentials',
      'Cat Essentials',
      'Fish & Aquatic',
      'Pet Grooming & Hygiene',
      'Pet Toys',
      'Pet Health & Safety',
    ],
  },
  appliances: {
    Televisions: ['MORE IN TELEVISIONS',
      'All',
      'New Launches',
      'Top Sellers',
      '24-32 Inch',
      '40-43 Inch',
      '50-55 Inch',
      'Big Screen TVs',
      'Smart TVs',
      '4K UHD TVs',
      'The Frame',
      'OLED TVs',
      'QLED TVs',
      'Nanocell TVs'],
    'Washing Machines': [
      ' MORE IN WASHING MACHINES',
      'All',
      'New Launches',
      'Fully Automatic Front Load',
      'Semi Automatic Top Load',
      'Fully Automatic Top Load',
      'Washer Dryers',
      'Washer Only',
      'Dishwashers',
      'Energy Efficient',
      '#JustHere',
      'Bestsellers',
      'Top Brands',
    ],
    'Air Conditioners': [
      'MORE IN AIR CONDITIONERS',
      'All',
      'New Launches',
      'Inverter ACs',
      'Split ACs',
      'Window ACs',
      '#justHere',
      'Energy Efficient ACs',
      '5 Star ACs',
      'Best sellers',
      '1 Ton ACs',
      '1.5 Ton ACs',
      'Wi-fi Enabled',
      'Top Brands',
    ],
    Refrigerators: ['MORE IN REFRIGERATORS',
      'All',
      'New Launches',
      'Single Door',
      'Double Door',
      'Triple door',
      'Side by Side',
      '4 Door',
      'Mini Refrigerators',
      'Convertible',
      'Bottom Mount',
      'Energy-Efficient'],
    'Kitchen Appliances': ['MORE IN KITCHEN APPLIANCES',
      'All',
      'New Launches',
      'Microwave Ovens',
      'Oven Toaster Grills (OTG)',
      'Juicer/Mixer/Grinder',
      'Electric Kettle',
      'Induction Cooktops',
      'Chimneys',
      'Coffee Makers',
      'Sandwich Makers',
      'Pop Up Toasters',
      'Electric Cookers',
      'Wet Grinders'],
    'Home Appliances': ['MORE IN HOME APPLIANCES',
      'All',
      'New Launches',
      'Irons',
      'Water Purifiers',
      'Inverters',
      'Vacuum Cleaners',
      'Sewing Machines',
      'Voltage Stabilizers',
      'Air Purifiers',
      'Landline Phones'],
    'Seasonal Appliances': ['MORE IN SEASONAL APPLIANCES',
      'All',
      'New Launches',
      'Air Coolers',
      'Fans',
      'Water Geysers',
      'Immersion Rods',
      'Room Heater'],
    'Premium Appliances': ['MORE IN PREMIUM APPLIANCES',
      'All',
      'Premium Televisions',
      'Premium Washing Machines',
      'Side By Side Refrigerators',
      'Vacuum Cleaners',
      'Dishwashers',
      'Premium ACs',
      'Designer Fans',
      'Washer dryers',
      'Four Door Refrigerators'],
    'Buying Guides': ['MORE IN BUYING GUIDES',
      'All',
      'Televisions',
      'Washing Machines',
      'Refrigerators',
      'Air Conditioners',
      'Water Purifiers',
      'Air Purifiers',
      'Chimneys',
      'Water Geysers'],
    'Flipkart Benefits': ['MORE IN FLIPKART BENEFITS',
      'All',
      'Exchange Offers',
      'No Cost EMI',
      'Extended Warranty',
      'Complete Appliance Protection',
      'Save More on Business Purchase',
      'Appliance Service Plan'],
  },
  BeautyToysAndMore: {
    'Beauty & Personal Care': ['MORE IN BEAUTY & PERSONAL CARE',
      'View All',
      'Bath & Oral Care',
      'Personal Hygiene',
      'Eye Makeup',
      'Face Makeup',
      'Lip Makeup',
      'Hair Care',
      'Bath Essentials',
      'Womens Personal Hygiene',
      'Body & Skin Care',
      'Luxury',
      'Top Brand Deals'],
    'Mens Grooming': ['MORE IN MENS GROOMING',
      'View All',
      'Face Washes',
      'Beard Oils',
      'Hair Styling',
      'Shaving Essentials',
      'Aftershave',
      'Face Creams & Face Packs',
      'Soaps & Bodywashes',
      'Mens Grooming Combos',
      'Sexual Wellness'],
    'Food & Drinks': ['MORE IN FOOD & DRINKS',
      'View All',
      'Beverages',
      'Nuts & Dry Fruits',
      'Cooking Essentials',
      'Breakfast Items',
      'Snacks Corner',
      'Jams, spreads & Honey',
      'Ready to Cook & Eat',
      'Chocolates',
      'Baking Essentials',
      'Sweets Store',
      'Top Brand Deals'],
    'Nutrition & Health Care': ['MORE IN NUTRITION & HEALTH CARE',
      'View All',
      'Masks',
      'Ayurvedic Supplements',
      'Health Drinks',
      'Vitamin Supplements',
      'Protein Supplements',
      'Womens Safety',
      'Home Medicines',
      'Home Medical Supplies',
      'Healthcare Comos',
      'Professional Medical Supplies',
      'Top Brand Deals'],
    'Baby Care': ['MORE IN BABY CARE',
      'View All',
      'Baby Diapers',
      'Baby Wipes',
      'Baby Bath & Grooming',
      'Baby Gift Sets & Combo',
      'Baby Medical & Health Care',
      'Nursing & Breast Feeding',
      'Feeding Bottles, Utensils & Accessories',
      'Baby Food',
      'Baby Bedding',
      'Baby Gear',
      'Top Brand Deals'],
    'Toys & School Supplies': ['MORE IN TOYS & SCHOOL SUPPLIES',
      'View All',
      'Remote Control Toys',
      'Soft Toys',
      'Puzzles',
      'Board Games',
      'Learning & Educational Toys',
      'Cars & Die-Cast Vehicles',
      'Baby Toys',
      'Gifting Toys',
      'School Bags & Backpacks',
      'School Supplies',
      'Top Brand Deals'],
    'Sports & Fitness': ['MORE IN SPORTS & FITNESS',
      'View All',
      'Badminton',
      'Cricket',
      'Cycling',
      'Football',
      'Fitness Equipments',
      'Supports',
      'Shakers & Sippers',
      'Gym Gloves',
      'Dumbbells',
      'Yoga',
      'Top Brand Deals'],
    'Books & Music': ['MORE IN BOOKS & MUSIC',
      'View All',
      'Test prep',
      'Academics',
      'Literature & Fiction',
      'Non Fiction',
      'Young Readers',
      'E-Learning',
      'Indian Languages',
      'Acoustic Guitars',
      'Musical keyboards',
      'Microphones',
      'Stage Equipment & Accessories'],
    'Stationery & Office Supplies': ['MORE IN STATIONERY & OFFICE SUPPLIES',
      'View All',
      'Pens & Gift Sets',
      'Notebooks & Diaries',
      'Art Supplies',
      'Calculators',
      'Keychains',
      'Card Holders',
      'Desk Organizers',
      'Office Supplies',
      'Office Equipments',
      'Party Supplies',
      'Top Brand Deals'],
    'Auto Accessories': ['MORE IN AUTO ACCESSORIES',
      'View All',
      'Bike Essentials',
      'Car & Bike Covers',
      'CarAirFreshener',
      'CarBluetoothDevice',
      'CarLubricant',
      'CarVacuumCleaner',
      'CarMediaPlayer',
      'Helmet',
      'Vehicle Washing & Cleaning Products',
      'Tyres',
      'Top Brand Deals'],
    'Safety & Hygiene Essentials': ['MORE IN SAFETY & HYGIENE ESSENTIALS',
      'View All',
      'Masks',
      'Sanitizers',
      'Hand Wash',
      'Gloves',
      'PPE Kits',
      'Face Shields',
      'UV Sterilizer Box',
      'Safety Goggles',
      'Vitamins for Immunity'],
  },
};

export const brandDirectory = {
  'MOST SEARCHED FOR ON FLIPKART': ['iPhone 13', 'iPhone 13 Pro', 'iPhone 13 Pro Max', 'iPhone 13 Mini', 'Flipkart Quick', 'Books', 'Flipkart Help Centre', 'Flipkart Track Orders', 'Flipkart Manage Orders', 'Flipkart Return Orders', 'Flipkart Gift Cards Store', 'Flipkart Axis Bank Credit Card', 'Flipkart Pay Later'],
  MOBILES: ['iPhone 12 64GB', 'iPhone 12 Pro 512GB', 'iPhone 12 128GB', 'Vivo Y91i', 'Vivo Y11', 'Vivo Y15', 'Vivo Y50', 'Vivo Y12', 'Reno2 F', 'Oppo A12', 'Oppo F15', 'Oppo A31', 'Samsung A71', 'Samsung A51', 'Samsung A31', 'Realme X2', 'iPhone 11', 'iPhone 11 Pro', 'iPhone 11 Pro MaxMobile Offers', 'iphone x4G Mobile', 'Nokia Mobile', 'Samsung Mobileiphone', 'Oppo Mobile', 'Vivo Mobile'],
  CAMERA: ['GoPro Action Camera', 'Nikon Camera', 'Canon Camera', 'Sony Camera', 'Canon DSLR', 'Nikon DSLR'],
  LAPTOPS: ['Microsoft Surface Go Pentium Gold 64GB', 'Microsoft Surface Go Pentium 128GB', 'Branded Laptops', 'Apple Laptops', 'Acer Laptops', 'Lenovo Laptops', 'Dell Laptops', 'Asus Laptops', 'HP Laptops', 'Gaming Laptops', '2 in 1 Laptops', 'Business Laptops'],
  TVS: ['Nokia TV', 'Panasonic TV', 'Thomson TV', 'Vu TV', 'Realme TV', 'Motorola TV', 'OnePlus TVs', 'LG TVTV', 'Sony TV', 'Samsung TV', 'Android Television', 'Iffalcon Tv', 'Mi TV'],
  'LARGE APPLIANCES': ['Washing Machines', 'Refrigerators', 'Air Conditioners', 'Electric Cookers', 'Electric Jug(Heater) / Travel Kettles', 'Induction Cooktops', 'Inverters / stabilizer', 'Irons / Iron Box', 'Mixer Grinder Juicer', 'Wet Grinders', 'Chimneys', 'Microwave Ovens', 'Vacuum Cleaners', 'Water Purifier', 'Fan'],
  CLOTHING: ['Men Shirts', 'Kurta Pajama', 'Kurtas', 'Men T-Shirts', 'Jeans', 'Saree', 'Dresses', 'Kids Dresses', 'Designer Salwar Suits', 'Bra', 'Designer Kurtis', 'Track Pant', 'Men Kurtas', 'Gym Wear', 'Party Dresses', 'Palazzo Suits', 'Boys Clothing', 'Gloves', 'Nighty', 'Maxi Dresses', 'Anarkali', 'Gowns', 'Culottes', 'Salwar Suits', 'KurtisDesigner Sarees', 'Leggings', 'Shorts', 'Georgette Sarees', 'Ethnic Wear', 'Briefs & Trunks'],
  FOOTWEAR: ['Shoes', 'Adidas Shoes', 'Reebok Shoes', 'Nike Shoes', 'Puma Shoes', 'Boots', 'Bata Shoes', 'Woodland Shoes', 'Skechers Shoes', 'Sneakers', 'Womens Boots', 'Sports Shoes', 'Loafers', 'Sandals', 'Lotto Sports Shoes', 'Casual Shoes', 'Womens Skechers Shoes', 'Asics Sports Shoes', 'Formal Shoes', 'School Shoes'],
  GROCERIES: ['PhonePe Grocery Voucher', 'Hand Wash', 'Soap', 'Cashew Nuts', 'Sunflower Oil', 'Eggs', 'Toilet Cleaner', 'Harpic Toilet Cleaner', 'Dettol Soap', 'Mustard Oil', 'Biscuits', 'Cheese', 'Patanjali Atta', 'Fortune Oil', 'Aashirvaad Atta', 'Tea'],
  'BEST SELLING ON FLIPKART': ['Bags', 'Samsung Galaxy Tab S7+', 'Books', 'Toys', 'Candles', 'Helmets', 'Wall Clocks', 'Baby Food', 'Chocolates', 'Cycles', 'Calculators', 'Lipsticks', 'Mask', 'Fastrack Watches', 'Wallets', 'Earrings', 'Gold Coins', 'Handbags'],
  FURNITURE: ['Grand Furniture Sale', 'Furniture', 'Sofas', 'Beds', 'Dining sets', 'Wardrobes', 'Mattresses', 'TV Units', 'Tables', 'Chairs', 'Shelves', 'Bean Bags', 'Office Chairs', 'Computer Table', 'Office Tables', 'Red Sofa', 'Wakefit Beds', 'White Sofa', 'Wakefit Mattress', 'Green Sofa', 'Black Sofa', 'Brown Sofa'],
};
